/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package mob.test;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int colorAccent=0x7f050002;
        public static final int colorControlHighlight=0x7f050003;
        public static final int colorControlNormal=0x7f050004;
        public static final int colorPrimary=0x7f050000;
        public static final int colorPrimaryDark=0x7f050001;
    }
    public static final class drawable {
        public static final int default_image=0x7f020000;
    }
    public static final class id {
        public static final int button5=0x7f080004;
        public static final int button7=0x7f080007;
        public static final int edittext1=0x7f080002;
        public static final int linear2=0x7f080003;
        public static final int linear5=0x7f080005;
        public static final int linear_main=0x7f080000;
        public static final int textview2=0x7f080001;
        public static final int textview4=0x7f080006;
    }
    public static final class layout {
        public static final int main=0x7f040000;
    }
    public static final class mipmap {
        public static final int ic_launcher=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f060000;
    }
    public static final class style {
        public static final int AppTheme=0x7f070000;
        public static final int FullScreen=0x7f070001;
        public static final int NoActionBar=0x7f070002;
        public static final int NoStatusBar=0x7f070003;
    }
}
