/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package mob.lifecycle;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int addFragmentButton=0x7f030001;
        public static final int fragmentContainer=0x7f030002;
        public static final int fragmentText=0x7f030000;
    }
    public static final class layout {
        public static final int fragment_layout=0x7f020000;
        public static final int main=0x7f020001;
    }
}
